steps:
  # Install dependencies
  - name: "node:16"
    entrypoint: "npm"
    args: ["install"]
    id: "install-deps"

  # Run tests and generate coverage reports
  - name: "node:16"
    entrypoint: "npm"
    args: ["test", "--", "--coverage"]
    id: "run-tests"

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile.dev",
        "-t",
        "gcr.io/rich-torus-428117-m8/nextjs-dockerized-template:$COMMIT_SHA",
        ".",
      ]
    id: "build-image"

  # Push Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/rich-torus-428117-m8/nextjs-dockerized-template:$COMMIT_SHA",
      ]
    id: "push-image"
    waitFor: ["build-image"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "nextjs-dockerized-template",
        "--image",
        "gcr.io/rich-torus-428117-m8/nextjs-dockerized-template:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
    id: "deploy"
    waitFor: ["push-image"]

  # Run SonarQube analysis
  - name: "node:16"
    entrypoint: "/bin/sh"
    args:
      [
        "-c",
        "curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip && unzip sonar-scanner.zip -d /opt && /opt/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.projectKey=lolo-frontend -Dsonar.sources=. -Dsonar.host.url=http://35.193.96.87:9001 -Dsonar.login=sqp_fbf1d71249cd4716699619847b5d5661a0755521 -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report.html -X",
      ]
    id: "sonar-analysis"
    waitFor: ["run-tests"]

  # Check SonarQube quality gate status
  - name: "node:16"
    entrypoint: "/bin/sh"
    args:
      [
        "-c",
        "PROJECT_KEY='lolo-frontend'\nSONAR_HOST='http://35.193.96.87:9001'\nSONAR_TOKEN='squ_3f583409bb9c564cfaca350e4fd4bb70f4da7542'\nCE_TASK_ID=$(curl -u $SONAR_TOKEN: $SONAR_HOST/api/ce/component?component=$PROJECT_KEY | jq -r '.current.id')\necho $CE_TASK_ID\nQUALITY_GATE_STATUS=$(curl -u $SONAR_TOKEN: $SONAR_HOST/api/ce/task?id=$CE_TASK_ID | jq -r '.task.status')\necho $QUALITY_GATE_STATUS\nif [ \"$QUALITY_GATE_STATUS\" = \"SUCCESS\" ]; then\n  echo 'Quality Gate passed'\n  exit 0\nelse\n  echo 'Quality Gate failed'\n  exit 1\nfi",
      ]
    id: "check-quality-gate"
    waitFor: ["sonar-analysis"]

# Substitutions for environment variables
substitutions:
  _REGION: us-central1

# Cloud Build options
options:
  logging: CLOUD_LOGGING_ONLY
