steps:
  # Install dependencies
  - name: "node:16"
    entrypoint: "npm"
    args: ["install"]
    id: "install-deps"

  # Run tests and generate coverage reports
  - name: "node:16"
    entrypoint: "npm"
    args: ["test", "--", "--coverage"]
    id: "run-tests"

  # Download SSH private key from Secret Manager and print it
  #  yo pani afno vm jasto ho so afno vm ma mkdir gareko tya store gareko aaba yah bata uta vm ma access garne
  - name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Ensure the .ssh directory exists
        mkdir -p /root/.ssh
        # Fetch the SSH private key from Secret Manager
        gcloud secrets versions access latest --secret="YOUR_SECRET_NAME" > /root/.ssh/id_rsa
        # Ensure the private key has the correct permissions
        chmod 600 /root/.ssh/id_rsa
        # Print the private key to verify (for debugging, remove this in production)
        cat /root/.ssh/id_rsa

  # # Upload coverage reports to VM
  # - name: "alpine"
  #   entrypoint: "sh"
  #   args:
  #     - "-c"
  #     - |
  #       apk add --no-cache openssh-client
  #       scp -o StrictHostKeyChecking=no -r coverage/lcov-report/* bishal@34.41.188.85:/var/www/html/coverage/
  #   id: "upload-coverage"
  #   waitFor: ["run-tests"]

  - name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache openssh-client
        scp -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -r coverage/lcov-report/* bishal@34.41.188.85:/var/www/html/coverage/
    id: "upload-coverage"
    waitFor: ["run-tests"]

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile.dev",
        "-t",
        "gcr.io/rich-torus-428117-m8/nextjs-dockerized-template:$COMMIT_SHA",
        ".",
      ]
    id: "build-image"
    # waitFor: ["upload-coverage"]

  # Push Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/rich-torus-428117-m8/nextjs-dockerized-template:$COMMIT_SHA",
      ]
    id: "push-image"
    waitFor: ["build-image"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "nextjs-dockerized-template",
        "--image",
        "gcr.io/rich-torus-428117-m8/nextjs-dockerized-template:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
    id: "deploy"
    waitFor: ["push-image"]

# Substitutions for environment variables
substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
