# Use the official Node.js image as the base image
FROM node:18-alpine as baseImage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# # now serve this out/index.html with nginx
FROM nginx:1.26-alpine
WORKDIR /app
COPY --from=baseImage /app/out /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
