# Use the official Node.js image as the base image
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN mkdir -p /workspace 
RUN chmod 777 /workspace
COPY . .
CMD ["npm", "run", "dev"]